# Generated by Django 5.1.7 on 2026-06-18 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_key', models.CharField(choices=[('dashboard', 'Dashboard'), ('facultades', 'Facultades'), ('sedes', 'Sedes'), ('carreras', 'Carreras'), ('planes', 'Planes de Estudio'), ('areas', 'Áreas'), ('materias', 'Materias'), ('equivalencias', 'Equivalencias'), ('configuracion', 'Configuración'), ('configuracion.usuarios', 'Config. - Autorización usuarios'), ('configuracion.dominios', 'Config. - Dominios permitidos'), ('configuracion.roles', 'Config. - Roles de usuarios'), ('configuracion.tipos-materia', 'Config. - Tipos de Materia')], max_length=50)),
                ('can_read', models.BooleanField(default=False)),
                ('can_write', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_permissions', to='auth.group')),
            ],
            options={
                'verbose_name': 'Permiso de menú',
                'verbose_name_plural': 'Permisos de menú',
                'unique_together': {('group', 'menu_key')},
            },
        ),
    ]
