# Generated by Django 5.1.7 on 2026-06-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_groupmenupermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmenupermission',
            name='menu_key',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('facultades', 'Facultades'), ('sedes', 'Sedes'), ('carreras', 'Carreras'), ('planes', 'Planes de Estudio'), ('areas', 'Áreas'), ('materias', 'Materias'), ('docentes', 'Docentes'), ('equivalencias', 'Equivalencias'), ('configuracion', 'Configuración'), ('configuracion.usuarios', 'Config. - Autorización usuarios'), ('configuracion.dominios', 'Config. - Dominios permitidos'), ('configuracion.roles', 'Config. - Roles de usuarios'), ('configuracion.tipos-materia', 'Config. - Tipos de Materia')], max_length=50),
        ),
    ]
