# Generated by Django 5.1.7 on 2026-06-08 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equivalencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('total', 'Total'), ('parcial', 'Parcial')], default='total', max_length=20)),
                ('resolucion', models.CharField(blank=True, max_length=100)),
                ('porcentaje', models.PositiveSmallIntegerField(blank=True, help_text='Para equivalencia parcial', null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('materias_destino', models.ManyToManyField(related_name='equivalencias_destino', to='academica.materia')),
                ('materias_origen', models.ManyToManyField(related_name='equivalencias_origen', to='academica.materia')),
                ('plan_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equivalencias_destino', to='academica.planestudio')),
            ],
            options={
                'verbose_name': 'Equivalencia',
                'verbose_name_plural': 'Equivalencias',
                'ordering': ['-pk'],
            },
        ),
    ]
