# Generated by Django 5.1.7 on 2026-06-24 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Subdisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subdisciplinas', to='nomenclador.disciplina')),
            ],
            options={
                'verbose_name': 'Subdisciplina',
                'verbose_name_plural': 'Subdisciplinas',
                'ordering': ['disciplina__codigo', 'codigo'],
                'unique_together': {('codigo', 'disciplina')},
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('subdisciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='especialidades', to='nomenclador.subdisciplina')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['subdisciplina__disciplina__codigo', 'subdisciplina__codigo', 'codigo'],
                'unique_together': {('codigo', 'subdisciplina')},
            },
        ),
    ]
