# Generated by Django 5.1.7 on 2026-06-23 15:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academica', '0005_alter_materia_carga_horaria_semanal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Solo números.')])),
                ('cuit_cuil', models.CharField(blank=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\d{2}-\\d{8}-\\d$', 'Formato: XX-XXXXXXXX-X')])),
                ('legajo', models.CharField(blank=True, max_length=20)),
                ('legajo_en_tramite', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('facultad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docentes', to='academica.facultad')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
