# Generated by Django 5.1.7 on 2026-06-23 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='cuit_cuil',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{2}-\\d{8}-\\d$', 'Formato: XX-XXXXXXXX-X')]),
        ),
    ]
