# Generated by Django 5.1.7 on 2026-06-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0003_caracter_cargo_dedicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracter',
            name='requiere_fecha',
            field=models.CharField(choices=[('ninguna', 'Sin fechas'), ('inicio', 'Solo fecha de inicio'), ('fin', 'Solo fecha de fin'), ('ambas', 'Fecha de inicio y fin')], default='ninguna', max_length=10),
        ),
    ]
