# Generated by Django 5.1.7 on 2026-06-24 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0006_materia_disciplina_materia_especialidad_and_more'),
        ('docentes', '0004_caracter_requiere_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('caracter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos_docentes', to='docentes.caracter')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos_docentes', to='docentes.cargo')),
                ('dedicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos_docentes', to='docentes.dedicacion')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='docentes.docente')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos_docentes', to='academica.materia')),
            ],
            options={
                'verbose_name': 'Cargo de Docente',
                'verbose_name_plural': 'Cargos de Docentes',
                'ordering': ['docente__apellido', 'docente__nombre', 'materia__nombre'],
            },
        ),
    ]
