# Generated by Django 5.1.7 on 2026-06-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0005_cargodocente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargodocente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
