# Generated by Django 5.1.7 on 2026-06-24 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0006_materia_disciplina_materia_especialidad_and_more'),
        ('docentes', '0006_cargodocente_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargodocente',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos_docentes', to='academica.sede'),
        ),
    ]
