# Generated by Django 5.1.7 on 2026-06-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0006_materia_disciplina_materia_especialidad_and_more'),
        ('docentes', '0007_cargodocente_sede'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargodocente',
            options={'ordering': ['docente__apellido', 'docente__nombre'], 'verbose_name': 'Cargo de Docente', 'verbose_name_plural': 'Cargos de Docentes'},
        ),
        migrations.RemoveField(
            model_name='cargodocente',
            name='materia',
        ),
        migrations.AddField(
            model_name='cargodocente',
            name='materias',
            field=models.ManyToManyField(blank=True, related_name='cargos_docentes', to='academica.materia'),
        ),
    ]
