# Generated by Django 5.1.7 on 2026-06-08 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TituloIntermedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('duracion_anos', models.PositiveSmallIntegerField(help_text='Duración en años')),
            ],
            options={
                'verbose_name': 'Título Intermedio',
                'verbose_name_plural': 'Títulos Intermedios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre_corto', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=255)),
                ('activa', models.BooleanField(default=True)),
                ('decano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('codigo_ministerial', models.CharField(blank=True, default='', max_length=20)),
                ('nombre_corto', models.CharField(blank=True, default='', max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('titulo_otorga', models.CharField(blank=True, default='', max_length=255)),
                ('duracion_anos', models.PositiveSmallIntegerField(default=1)),
                ('nivel', models.CharField(choices=[('grado', 'Grado'), ('pregrado', 'Pregrado'), ('posgrado', 'Posgrado')], default='grado', max_length=20)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('distancia', 'Distancia'), ('mixta', 'Mixta')], default='presencial', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='academica.facultad')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['facultad', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código del plan de estudio', max_length=50)),
                ('version', models.CharField(blank=True, default='', help_text='Versión del plan', max_length=50)),
                ('titulo_otorga', models.CharField(help_text='Título que otorga', max_length=255)),
                ('duracion_anos', models.PositiveSmallIntegerField(help_text='Duración en años según el título que otorga')),
                ('año_inicio_implementacion', models.PositiveIntegerField(help_text='Año en que comenzó a implementarse')),
                ('vigente', models.BooleanField(default=False, help_text='Indica si el plan está vigente actualmente')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='academica.carrera')),
                ('titulos_intermedios', models.ManyToManyField(blank=True, to='academica.titulointermedio')),
            ],
            options={
                'verbose_name': 'Plan de Estudio',
                'verbose_name_plural': 'Planes de Estudio',
                'ordering': ['carrera', '-año_inicio_implementacion'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('año', models.PositiveSmallIntegerField()),
                ('cuatrimestre', models.CharField(choices=[('1', 'Primer Cuatrimestre'), ('2', 'Segundo Cuatrimestre'), ('anual', 'Anual')], max_length=10)),
                ('creditos', models.PositiveSmallIntegerField(blank=True, help_text='Créditos de la materia', null=True)),
                ('periodo', models.CharField(blank=True, default='', help_text='Período original (ej: B1/1C, 1C, B2/1C)', max_length=20)),
                ('carga_horaria_semanal', models.PositiveIntegerField()),
                ('carga_horaria_total', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('obligatoria', 'Obligatoria'), ('optativa', 'Optativa'), ('electiva', 'Electiva')], max_length=20)),
                ('contenidos_minimos', models.TextField(blank=True)),
                ('plan_estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='academica.planestudio')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['plan_estudio', 'año', 'cuatrimestre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('activa', models.BooleanField(default=True)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('localidad', models.CharField(blank=True, default='', max_length=100)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='academica.facultad')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['facultad', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='carrera',
            name='sedes',
            field=models.ManyToManyField(blank=True, related_name='carreras', to='academica.sede'),
        ),
        migrations.CreateModel(
            name='Correlatividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cursar', 'Para cursar'), ('cursado', 'Cursado'), ('aprobar', 'Para aprobar'), ('aprobacion', 'Aprobación'), ('regular', 'Regular')], max_length=20)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlativas', to='academica.materia')),
                ('materia_requerida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisito_de', to='academica.materia')),
            ],
            options={
                'verbose_name': 'Correlatividad',
                'verbose_name_plural': 'Correlatividades',
                'unique_together': {('materia', 'materia_requerida', 'tipo')},
            },
        ),
        migrations.AddIndex(
            model_name='materia',
            index=models.Index(fields=['plan_estudio', 'año'], name='academica_m_plan_es_24feba_idx'),
        ),
        migrations.AddIndex(
            model_name='materia',
            index=models.Index(fields=['plan_estudio', 'codigo'], name='academica_m_plan_es_bbff7f_idx'),
        ),
        migrations.AddIndex(
            model_name='materia',
            index=models.Index(fields=['tipo'], name='academica_m_tipo_c1a54b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='materia',
            unique_together={('plan_estudio', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='sede',
            unique_together={('facultad', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='carrera',
            unique_together={('facultad', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='planestudio',
            index=models.Index(fields=['carrera', 'vigente'], name='academica_p_carrera_985969_idx'),
        ),
        migrations.AddIndex(
            model_name='planestudio',
            index=models.Index(fields=['año_inicio_implementacion'], name='academica_p_año_ini_092fce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='planestudio',
            unique_together={('carrera', 'codigo')},
        ),
    ]
