# Generated by Django 5.1.7

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academica", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoMateria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tipo de Materia",
                "verbose_name_plural": "Tipos de Materia",
                "ordering": ["nombre"],
            },
        ),
        migrations.AlterField(
            model_name="materia",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="materias",
                to="academica.tipomateria",
            ),
        ),
    ]
