# Generated by Django 5.1.7

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academica", "0002_tipomateria_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "plan_estudio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas",
                        to="academica.planestudio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Área",
                "verbose_name_plural": "Áreas",
                "ordering": ["plan_estudio", "orden", "nombre"],
                "unique_together": {("plan_estudio", "nombre")},
            },
        ),
        migrations.AddField(
            model_name="materia",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="materias",
                to="academica.area",
            ),
        ),
    ]
