# Generated by Django 5.1.7 on 2026-06-12 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0003_area_materia_area'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='materia',
            name='academica_m_tipo_c1a54b_idx',
        ),
    ]
