# Generated by Django 5.1.7 on 2026-06-19 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0004_remove_materia_academica_m_tipo_c1a54b_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='carga_horaria_semanal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materias', to='academica.tipomateria'),
        ),
    ]
