# Generated by Django 5.1.7 on 2026-06-24 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0005_alter_materia_carga_horaria_semanal_and_more'),
        ('nomenclador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materias', to='nomenclador.disciplina'),
        ),
        migrations.AddField(
            model_name='materia',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materias', to='nomenclador.especialidad'),
        ),
        migrations.AddField(
            model_name='materia',
            name='nomenclador_free_text',
            field=models.CharField(blank=True, default='', help_text='Texto libre cuando el código del nomenclador es 99 (OTRAS)', max_length=255),
        ),
        migrations.AddField(
            model_name='materia',
            name='subdisciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materias', to='nomenclador.subdisciplina'),
        ),
    ]
