# Generated by Django 5.1.7 on 2026-08-13 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0006_materia_disciplina_materia_especialidad_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Correlatividad',
        ),
    ]
